version: '3.8'

services:
  whatsapp-bot:
    image: browserless/chrome:1.61-chrome-stable
    container_name: whatsapp-crpyto-bot
    user: root                        
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app                
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - CHROME_PATH=/usr/bin/google-chrome
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
      - PUPPETEER_WS_ENDPOINT=ws://localhost:3000

volumes:
  node_modules:                      
  ollama_data:
