// //own wallet address passed as param, contract address, network as param, calls mint

// “Pyth Entropy Pool Prize”

// Your app should consume random number generated by Pyth. Please follow along the guides and Tutorials to get started.
